# Generated by Django 6.0.1 on 2026-01-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth_user_phone_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-profile-image.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
