# Generated by Django 6.0.1 on 2026-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-profile-image.jpg', upload_to='profile_pics/'),
        ),
    ]
