# Generated by Django 6.0.1 on 2026-01-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video link for this course', max_length=1000, null=True),
        ),
    ]
