# Generated by Django 6.0.1 on 2026-01-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='default', upload_to='course_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='video_url',
            field=models.URLField(default='fds', help_text='YouTube video link for this course', max_length=1000),
            preserve_default=False,
        ),
    ]
