# Generated by Django 6.0.1 on 2026-01-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_image_alter_courses_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='video_url',
            field=models.URLField(max_length=1000),
        ),
    ]
